
import { type SpreadTalk } from '@/lib/spread-reading/types';
import { logApiCall } from '@/lib/db/queries/api-usage';

// Context for API call logging (optional)
export interface ApiCallContext {
  sessionId?: string;
  source?: string;
}

const TED_CHANNEL_ID = 'UCAuUUnT6oDeKwE6v1NGQxug';
const TEDX_CHANNEL_ID = 'UCsT0YIqwnpJCM-mx7-gSA4Q';

// Read API key at runtime, not module load time
function getYouTubeApiKey(): string | undefined {
  return process.env.YOUTUBE_API_KEY;
}

export interface YouTubeResult {
    id: string;
    title: string;
    description: string;
    channelTitle: string;
    thumbnail: string;
    publishedAt: string;
    url: string;
    source: 'youtube';
}

/**
 * Clean the query generated by Gemini to get a raw search term
 * and optionally identify a target channel.
 */
function parseQuery(query: string, defaultToTed: boolean = false): { term: string; channelId?: string } {
    let term = query;
    let channelId: string | undefined;

    // Check for explicit channel mentions in the query string format from Gemini
    // "site:youtube.com/@TED keywords"
    if (term.includes('@TEDx')) {
        channelId = TEDX_CHANNEL_ID;
        term = term.replace(/site:youtube\.com\/@TEDx/gi, '').replace(/@TEDx/gi, '');
    } else if (term.includes('@TED')) {
        channelId = TED_CHANNEL_ID;
        term = term.replace(/site:youtube\.com\/@TED/gi, '').replace(/@TED/gi, '');
    }

    // Clean up any remaining site: syntax
    term = term.replace(/site:youtube\.com\S*/gi, '').trim();

    // If no channel specified and defaultToTed is true, default to TED channel
    // This ensures fallback queries don't return random audiobooks/unrelated content
    if (!channelId && defaultToTed) {
        channelId = TED_CHANNEL_ID;
    }

    return { term, channelId };
}

/**
 * Search YouTube for a specific query
 * Returns results and status info for logging
 */
async function searchOne(
    query: string,
    maxResults: number = 2,
    defaultToTed: boolean = false
): Promise<{ results: YouTubeResult[]; status: number; error?: string }> {
    const apiKey = getYouTubeApiKey();
    if (!apiKey) {
        console.warn('YOUTUBE_API_KEY not configured');
        return { results: [], status: 0, error: 'not_configured' };
    }

    const { term, channelId } = parseQuery(query, defaultToTed);

    // Build URL
    const url = new URL('https://www.googleapis.com/youtube/v3/search');
    url.searchParams.append('part', 'snippet');
    url.searchParams.append('maxResults', maxResults.toString());
    url.searchParams.append('q', term);
    url.searchParams.append('type', 'video');
    url.searchParams.append('key', apiKey);
    // Filter to medium duration videos (3-30 min) - ideal for TED talks
    url.searchParams.append('videoDuration', 'medium');

    if (channelId) {
        url.searchParams.append('channelId', channelId);
    }

    try {
        const response = await fetch(url.toString());

        if (!response.ok) {
            console.error(`YouTube API Error: ${response.status} ${response.statusText}`);
            return { results: [], status: response.status, error: response.statusText };
        }

        const data = await response.json();

        if (!data.items) return { results: [], status: 200 };

        const results = data.items.map((item: any) => ({
            id: item.id.videoId,
            title: item.snippet.title,
            description: item.snippet.description,
            channelTitle: item.snippet.channelTitle,
            thumbnail: item.snippet.thumbnails?.high?.url || item.snippet.thumbnails?.default?.url,
            publishedAt: item.snippet.publishedAt,
            url: `https://www.youtube.com/watch?v=${item.id.videoId}`,
            source: 'youtube'
        }));

        return { results, status: 200 };

    } catch (error) {
        console.error('YouTube search failed:', error);
        return { results: [], status: 0, error: error instanceof Error ? error.message : 'network_error' };
    }
}

export interface SearchYouTubeOptions {
    defaultToTed?: boolean; // Default to TED channel if no channel specified in query
}

/**
 * Run multiple search queries in parallel and deduplicate results
 */
export async function searchYouTube(
    queries: string[],
    context?: ApiCallContext,
    options?: SearchYouTubeOptions
): Promise<YouTubeResult[]> {
    if (!getYouTubeApiKey()) {
        console.log('Skipping YouTube search: No API Key');
        return [];
    }

    const defaultToTed = options?.defaultToTed ?? false;

    // Run searches in parallel
    const searchPromises = queries.map(q => searchOne(q, 2, defaultToTed));
    const searchResults = await Promise.all(searchPromises);

    // Track overall status for logging
    let hasError = false;
    let errorType: 'rate_limit' | 'quota_exceeded' | 'network' | 'api_error' | undefined;
    let errorStatus: number | undefined;

    // Flatten and collect results
    const allResults: YouTubeResult[] = [];

    for (const { results, status, error } of searchResults) {
        if (status === 403) {
            // YouTube 403 typically means quota exceeded
            hasError = true;
            errorType = 'quota_exceeded';
            errorStatus = status;
        } else if (status === 429) {
            hasError = true;
            errorType = 'rate_limit';
            errorStatus = status;
        } else if (status === 0 || error) {
            hasError = true;
            errorType = 'network';
        } else if (status !== 200) {
            hasError = true;
            errorType = 'api_error';
            errorStatus = status;
        }

        allResults.push(...results);
    }

    // Dedup by Video ID
    const seen = new Set<string>();
    const uniqueResults: YouTubeResult[] = [];

    for (const r of allResults) {
        if (!seen.has(r.id)) {
            seen.add(r.id);
            uniqueResults.push(r);
        }
    }

    // Prepare detailed results for logging
    const resultsForLog = uniqueResults.slice(0, 10).map(r => ({
        id: r.id,
        title: r.title.slice(0, 100), // Truncate for storage
        channel: r.channelTitle,
    }));

    // Log the API call (once per searchYouTube call, not per query)
    // Include detailed query and result info for debugging
    if (hasError && uniqueResults.length === 0) {
        // Complete failure
        logApiCall({
            apiName: 'youtube',
            success: false,
            errorType,
            sessionId: context?.sessionId,
            source: context?.source,
            properties: {
                queriesCount: queries.length,
                queries: queries, // Log actual queries sent
                status: errorStatus,
                defaultToTed,
            },
        });
    } else if (hasError) {
        // Partial success (some queries failed, some succeeded)
        logApiCall({
            apiName: 'youtube',
            success: true, // Count as success since we got results
            sessionId: context?.sessionId,
            source: context?.source,
            properties: {
                queriesCount: queries.length,
                queries: queries,
                resultsCount: uniqueResults.length,
                results: resultsForLog,
                partialError: errorType,
                defaultToTed,
            },
        });
    } else {
        // Full success
        logApiCall({
            apiName: 'youtube',
            success: true,
            sessionId: context?.sessionId,
            source: context?.source,
            properties: {
                queriesCount: queries.length,
                queries: queries,
                resultsCount: uniqueResults.length,
                results: resultsForLog,
                defaultToTed,
            },
        });
    }

    return uniqueResults;
}
