
import { type SpreadTalk } from '@/lib/spread-reading/types';

const YOUTUBE_API_KEY = process.env.YOUTUBE_API_KEY;
const TED_CHANNEL_ID = 'UCAuUUnT6oDeKwE6v1NGQxug';
const TEDX_CHANNEL_ID = 'UCsT0YIqwnpJCM-mx7-gSA4Q';

export interface YouTubeResult {
    id: string;
    title: string;
    description: string;
    channelTitle: string;
    thumbnail: string;
    publishedAt: string;
    url: string;
    source: 'youtube';
}

/**
 * Clean the query generated by Gemini to get a raw search term
 * and optionally identify a target channel.
 */
function parseQuery(query: string): { term: string; channelId?: string } {
    let term = query;
    let channelId: string | undefined;

    // Check for explicit channel mentions in the query string format from Gemini
    // "site:youtube.com/@TED keywords"
    if (term.includes('@TEDx')) {
        channelId = TEDX_CHANNEL_ID;
        term = term.replace(/site:youtube\.com\/@TEDx/gi, '').replace(/@TEDx/gi, '');
    } else if (term.includes('@TED')) {
        channelId = TED_CHANNEL_ID;
        term = term.replace(/site:youtube\.com\/@TED/gi, '').replace(/@TED/gi, '');
    }

    // Clean up any remaining site: syntax
    term = term.replace(/site:youtube\.com\S*/gi, '').trim();

    return { term, channelId };
}

/**
 * Search YouTube for a specific query
 */
async function searchOne(query: string, maxResults: number = 2): Promise<YouTubeResult[]> {
    if (!YOUTUBE_API_KEY) {
        console.warn('YOUTUBE_API_KEY not configured');
        return [];
    }

    const { term, channelId } = parseQuery(query);

    // Build URL
    const url = new URL('https://www.googleapis.com/youtube/v3/search');
    url.searchParams.append('part', 'snippet');
    url.searchParams.append('maxResults', maxResults.toString());
    url.searchParams.append('q', term);
    url.searchParams.append('type', 'video');
    url.searchParams.append('key', YOUTUBE_API_KEY);

    if (channelId) {
        url.searchParams.append('channelId', channelId);
    } else {
        // If no channel specific, maybe search for "TED" in the query?
        // or just rely on the query term containing "TED"
    }

    try {
        const response = await fetch(url.toString());

        if (!response.ok) {
            console.error(`YouTube API Error: ${response.status} ${response.statusText}`);
            return [];
        }

        const data = await response.json();

        if (!data.items) return [];

        return data.items.map((item: any) => ({
            id: item.id.videoId,
            title: item.snippet.title,
            description: item.snippet.description,
            channelTitle: item.snippet.channelTitle,
            thumbnail: item.snippet.thumbnails?.high?.url || item.snippet.thumbnails?.default?.url,
            publishedAt: item.snippet.publishedAt,
            url: `https://www.youtube.com/watch?v=${item.id.videoId}`,
            source: 'youtube'
        }));

    } catch (error) {
        console.error('YouTube search failed:', error);
        return [];
    }
}

/**
 * Run multiple search queries in parallel and deduplicate results
 */
export async function searchYouTube(queries: string[]): Promise<YouTubeResult[]> {
    if (!YOUTUBE_API_KEY) {
        console.log('Skipping YouTube search: No API Key');
        return [];
    }

    // Run searches in parallel
    const resultsPromises = queries.map(q => searchOne(q, 2));
    const resultsArrays = await Promise.all(resultsPromises);

    // Flatten
    const allResults = resultsArrays.flat();

    // Dedup by Video ID
    const seen = new Set<string>();
    const uniqueResults: YouTubeResult[] = [];

    for (const r of allResults) {
        if (!seen.has(r.id)) {
            seen.add(r.id);
            uniqueResults.push(r);
        }
    }

    return uniqueResults;
}
